config/routes.rb
Rails.application.routes.draw do
  resources :miscs
  resources :videos
  resources :comments
  resources :games do
    resources :comments
  end

  mount Commontator::Engine => '/commontator'

  get "welcome/homepage"
   root 'welcome#homepage'
  
  get    'profiles' => 'profiles'
  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  get    'signup' => 'users#new'
  delete 'logout' => 'sessions#destroy'
  get    'about' => 'welcome#about'
  get    'contact' => 'welcome#contact'
  get    'allgames' => 'games#allgames'
  resources :users
end

app/models/misc.rb
class Misc < ApplicationRecord::Base
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/miscs_controller.rb
class MiscsController < ApplicationController
  before_action :set_misc, only: [:show, :edit, :update, :destroy]

  # GET /miscs
  # GET /miscs.json
  def index
    @miscs = Misc.all
  end

  # GET /miscs/1
  # GET /miscs/1.json
  def show
  end

  # GET /miscs/new
  def new
    @misc = Misc.new
  end

  # GET /miscs/1/edit
  def edit
  end

  # POST /miscs
  # POST /miscs.json
  def create
    @misc = Misc.new(misc_params)

    respond_to do |format|
      if @misc.save
        format.html { redirect_to @misc, notice: 'Misc was successfully created.' }
        format.json { render :show, status: :created, location: @misc }
      else
        format.html { render :new }
        format.json { render json: @misc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /miscs/1
  # PATCH/PUT /miscs/1.json
  def update
    respond_to do |format|
      if @misc.update(misc_params)
        format.html { redirect_to @misc, notice: 'Misc was successfully updated.' }
        format.json { render :show, status: :ok, location: @misc }
      else
        format.html { render :edit }
        format.json { render json: @misc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /miscs/1
  # DELETE /miscs/1.json
  def destroy
    @misc.destroy
    respond_to do |format|
      format.html { redirect_to miscs_url, notice: 'Misc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_misc
      @misc = Misc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def misc_params
      params.require(:misc).permit(:image, :popup)
    end
end

app/helpers/miscs_helper.rb
module MiscsHelper
end

app/views/miscs/_form.html.erb
<%= form_for(misc) do |f| %>
  <% if misc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(misc.errors.count, "error") %> prohibited this misc from being saved:</h2>

      <ul>
      <% misc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_area :image %>
  </div>

  <div class="field">
    <%= f.label :popup %>
    <%= f.text_area :popup %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/miscs/edit.html.erb
<h1>Editing Misc</h1>

<%= render 'form', misc: @misc %>

<%= link_to 'Show', @misc %> |
<%= link_to 'Back', miscs_path %>

app/views/miscs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Miscs</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Popup</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @miscs.each do |misc| %>
      <tr>
        <td><%= misc.image %></td>
        <td><%= misc.popup %></td>
        <td><%= link_to 'Show', misc %></td>
        <td><%= link_to 'Edit', edit_misc_path(misc) %></td>
        <td><%= link_to 'Destroy', misc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Misc', new_misc_path %>

app/views/miscs/new.html.erb
<h1>New Misc</h1>

<%= render 'form', misc: @misc %>

<%= link_to 'Back', miscs_path %>

app/views/miscs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @misc.image %>
</p>

<p>
  <strong>Popup:</strong>
  <%= @misc.popup %>
</p>

<%= link_to 'Edit', edit_misc_path(@misc) %> |
<%= link_to 'Back', miscs_path %>