config/routes.rb
Rails.application.routes.draw do
  resources :miscs
  resources :videos
  resources :comments
  resources :games do
    resources :comments
  end

  mount Commontator::Engine => '/commontator'

  get "welcome/homepage"
   root 'welcome#homepage'
  
  get    'profiles' => 'profiles'
  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  get    'signup' => 'users#new'
  delete 'logout' => 'sessions#destroy'
  get    'about' => 'welcome#about'
  get    'contact' => 'welcome#contact'
  get    'allgames' => 'games#allgames'
  resources :users
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
<div class="row">
<div class="col-lg-12">
<p>&copy; Powerplay</p>
</div>
</div>
<!-- /.row -->
</footer>

app/views/layouts/_header.html.erb
<!-- Navigation -->    
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<div class="container-fluid">

<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header" id="navbrand">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>

<!-- homepage -->
<a class="navbar-brand" href="/">PowerPlay</a>
</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav">

<!-- all games --> 
<li>
    <%= link_to "Game List", '/gamelist' %>
</li>

<!-- profile -->
<li>
<% if current_user %>
    <%= link_to "Profile", '/profiles' %>
</li>

<!-- logout -->
<li>
    <%= link_to "Log Out", logout_path, method: :delete %>
</li>

<!-- login -->
<li>
<% else %>
    <%= link_to "Login", '/login' %>
</li>

<!-- signup --> 
<li>
    <%= link_to "Signup", '/signup' %>
</li>
<% end %>
    
<!-- about --> 
<li>
    <%= link_to "About", '/about' %>
</li>
</ul>

<!-- search form -->
<%= form_tag(games_path, :method => "get", id: "search-form", target: "gamepages", class: 'navbar-form navbar-right') do %>
<div class="input-group">
  <%= search_field_tag :search, params[:search], placeholder: "Search Games" %>
  <%= button_to "Search", class: 'btn btn-default' %>
</div>
<% end %>
</div>
<!-- /.navbar-collapse -->
</div>
<!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>PowerPlay</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

  </head>

  <%= render "layouts/header" %>

  <div class="container">
    <body>
      <%= yield %>

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </body>
  </div>

  <%= render "layouts/footer" %>
</html>

app/views/layouts/comment.text.erb
<p id="notice"><%= notice %></p>
<br><br><br>
<h1>Comments</h1>
<br>
<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="15"></th>
      <th>Action</th>
      <th colspan="15"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
      <th colspan="15"></th>
        <td><%= comment.text %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>